config/routes.rb
Rails.application.routes.draw do
  
  resources :line_items
  resources :carts
  devise_for :users
  resources :books
  root to: 'books#index', as: 'book_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  # belongs_to :author
  # validates :book_title
  # has_one_attached :picture
  belongs_to :user
  has_many :line_items
  has_one_attached :picture
  validates :book_title, :author, :blurb, :price, :condition, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  before_destroy :ensure_not_referenced_by_any_line_item
  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
    errors.add(:base, 'Line Items present')
    throw :abort
  end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  load_and_authorize_resource
  

  # GET /books
  # GET /books.json
  def index
    # @books = Book.all
    @q =Book.ransack(params[:q])
    @books = @q.result.with_attached_picture
    
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
   def create
    @book = current_user.books.create(book_params)
    if @book.errors.any?
      render :new
    else
      flash[:success] = "You successfully created a new book!"
      redirect_to @book
    end 
  end
 

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_title, :author, :blurb, :price, :condition, :picture)
    end
    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_title %>
    <%= form.text_field :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :blurb %>
    <%= form.text_area :blurb %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition %>
  <div class="field">
  <%= form.label :picture %>
  <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image;jpg'%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if notice %>
<aside id="notice"><%= notice %></aside>
<% end %>

<h1>Books</h1>
<tr> 

<table>

 <p>Sort By: <%= sort_link(@q, :price, default_order: :asc) %></p>
 <p>Sort By: <%= sort_link(@q, :book_title, default_order: :asc) %></p>
<tr>

</tr>

<tbody>

<% @books.each do |book| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

<div class="card" style="width: 18rem;">
  <div class="photo"><%= image_tag book.picture if book.picture.attached?%></div>
  <div class="card-body">
    <h5 class="card-title"><%= book.book_title %></h5>
    <p class="card-text"><%= truncate(strip_tags(book.author),
length: 80) %></p>
    <p class="card-text"><%= truncate(strip_tags(book.blurb),
length: 80) %></p>
    <p class="card-text"><%= truncate(strip_tags(book.condition),
length: 80) %></p>
    <p class="card-text"><%= number_to_currency(book.price) %></p>
    <%= button_to 'Add to Cart', line_items_path(book_id: book) %>
    
    <%= link_to 'Show', book %>
    <% if user_signed_in? && (current_user == book.user)%>
    <%= link_to 'Edit', edit_book_path(book) %> 
    <%= link_to 'Destroy', book,
method: :delete,
data: { confirm: 'Are you sure?' }%>
<%end%>
  </div>
  </div>




</tr>
<% end %>
</tbody>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book title:</strong>
  <%= @book.book_title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Blurb:</strong>
  <%= @book.blurb %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @book.condition %>
</p>
<p>
<%= image_tag @book.picture if @book.picture.attached?%>
</p>
<div class="show-edit-delete">
   <% if can? :edit, @book %>
     <%= link_to "Edit", edit_book_path(@book.id) %>
     <%= link_to "Delete", book_path(@book.id), method: :delete %>
   <% end %>
   <%= link_to "Back", :back %>
 </div>